### ISSUE TITLE
Close method not called

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [feixuwu/UEWebsocket#1]
Everything works just fine, except the WebSocket is not closed properly. I tried to debug this, but the `Close` method in the `WebSocketBase` class isn't hit in debug mode.
On the server side it then tells me that the close handshake wasn't performed properly.

However, when I close the connection the close blueprint node the connection gets closed, but the closed event dispatcher is not called.

This is a serious issue and should be fixed as soon as possible

**Comment by feixuwu** [comment]
Hi, Yes, currently the close event will only trigger when remote closed, you the client call close, the event will not trigger.
I’ll fix the problem tomorrow. Before that, you can call close event on blueprint after you call the close node.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Robert Logiewa<mailto:notifications@github.com>
发送时间: 2017年9月8日 22:36
收件人: feixuwu/UEWebsocket<mailto:UEWebsocket@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [feixuwu/UEWebsocket] Close method not called (#1)


Everything works just fine, except the WebSocket is not closed properly. I tried to debug this, but the Close method in the WebSocketBase class isn't hit in debug mode.

However, when I close the connection qith the close blueprint node the connection gets closed, but the closed event dispatcher is not called.

This is a serious issue and should be fixed as soon as possible

―

**Comment by Ruhrpottpatriot** [comment]
Ah, great. Thanks for the head up. One additional thing: Could you write a word or two in the readme, how to use this plugin in c++? After I played around with it a bit I saw that can leverage many of my server talks from plain http requests to websockets.

**Comment by feixuwu** [comment]
fixed, no matter remote close or client call function close, will trigger the close event.
