### ISSUE TITLE
Attempting to use with Cortex websockets get a lws_sslclient_connect2 error

### ISSUE THREAD

**Issue by anadin** [feixuwu/UEWebsocket#12]
I am building an app that I need to connect to Cortex BCI's. They use a web socket api to talk to the devices now https://emotiv.github.io/cortex-docs/

But when I try to connect to wss://emotivcortex.com:54321 using UEWebsocket I get a connect error with this output

lws_ssl_client_connect2 failed

I've poked around in the source and stack exchange :) but I'm new to SSL and Sockets. Could you take a look?

I can connect to the endpoint fine at https://www.websocket.org/echo.html

**Comment by feixuwu** [comment]
Did you confirmed the 54321 port is available on emotivcortex.com?
you should first ask the service provider to confirm this service is valid.

**Comment by anadin** [comment]
Yup it is working and responding on that port which I tested using https://www.websocket.org/echo.html


It is the port in the SDK documentation too. I’m not 100% sure what other debug info/logging I can get out of UEWebsocket as that might help?




Sent with Unibox

**Comment by anadin** [comment]
Actually I think it could be the port? looking through the code it looks like you are defaulting to 443 if using SSL? could you check for the :XXXXX and use that or even offer a port entry on the connect node?

**Comment by feixuwu** [comment]
if you telnet the target 54321 port, you will find the port can not reachable, so the target service is not working. you can contact https://emotiv.github.io/cortex-docs/ to see if this service is work.

**Comment by anadin** [comment]
Yup, turns out that service is local, it adds itself to the hosts file. closing for now, I'll update if I ever get it working - thanks!
