### ISSUE TITLE
Blueprint is not saved after close UE

### ISSUE THREAD

**Issue by g-ericso** [feixuwu/UEWebsocket#14]
The plugin so far is working fine except we are unable to save the blueprint settings after shutdown UE. Is there any special command or procedure to save the blueprint using this plugin.

**Comment by feixuwu** [comment]
I did't understand, did you means the ip and port  in your blueprint?
Blueprint is saved by the engine it's self.

**Comment by 4ossiblellc** [comment]
The linkage between the nodes of blueprints were gone. We need to refresh all connected nodes. It seems the engine did not save the settings. Just wondering if anyone is having the same issue.

**Comment by feixuwu** [comment]
Did you saved your work or save all before close unreal engine editor?
