### ISSUE TITLE
What license is this under?

### ISSUE THREAD

**Issue by hach-que** [feixuwu/UEWebsocket#15]
The LICENSE file in the root of the repository shows `MIT License`, but the header of some of the files is `LGPL`.

What's the actual license of this software? (LGPL is probably not compatible with UE4's license and/or the way UE4 builds executables anyway).

**Comment by Cl1608Ho** [comment]
Same question.

Mit would be awesome. However, if you look closely, UE4 itself ships with libwebsockets, which is at best available under lgpl. It's the only lib I ever looked at license-wise, and it's statically linked. One could argue about the engine being open source enough for that, but certainly not games created with it. I do not know about the status of other libs, but apparently noone really cares. Sadly.

Pleade please mit

**Comment by hach-que** [comment]
libwebsockets has an exception to the LGPL that excepts static linking:

```
2) Static linking of programs with the libwebsockets library does not
constitute a derivative work and does not require the author to provide 
source code for the program, use the shared libwebsockets libraries, or
link their program against a user-supplied version of libwebsockets.
```

However, my question is not "what license is libwebsockets under?", but rather "what license are the source code files in this repository under?".

This is because code in libwebsockets IS covered by the exemption, but code in this repository IS NOT covered by the exemption, because it's not libwebsockets code. But making these files LGPL without a static linking exception is incompatible with UE4's license because UE4 can not be LGPL.

We're going to proceed as if the `MIT` license at the root of the repository is the intended license for these files and assume that the `LGPL` headers have just been accidentally copied from libwebsockets when the code was written, since licensing under LGPL doesn't result in software or source code that can be distributed or linked together under any circumstances.

However, it would be much more ideal if the author of this repository would update the headers of these files to be MIT license to match the license in the root of the repository, so that there's no inconsistency.

**Comment by Cl1608Ho** [comment]
Oh, I missed that clause, resolves a lot for me haha. As long as we do not have clarification, I would say the same, especially as this is a line clearly written by the author himself, in the Readme

> This is an open source project, you can use it free.

He probably wanted to write use it freely, which in my opinion includes the right to use it without any further implications.

**Comment by feixuwu** [comment]
yes, you are right, use it to do any thing you want to do. you don't need to pay me, you can change the code freely.
I'm not a lawyer, the libwebsocket is distributed with binary, so I think it is fine?

**Comment by hach-que** [comment]
In that case, we've updated the source code of this library that we distribute to have the following header in files instead of LGPL:

```
/*
* Copyright (C) 2017 feiwu <feixuwu@outlook.com>
*
* The previous licensing header on this file has been replaced with this
* MIT license notice to make it consistent the LICENSE file contained in the
* original repository, as outlined in https://github.com/feixuwu/UEWebsocket/issues/15.
*/
```
