### ISSUE TITLE
Secure Sockets?

### ISSUE THREAD

**Issue by Merethiel** [feixuwu/UEWebsocket#17]
Does this library support connections through both ws and wss? I have a game server running under secure websockets and I would like to connect from a secure location as well since the website the game would be hosted on also has an ssl certificate.

**Comment by feixuwu** [comment]
yes, the demo project is connect with wss://echo.websocket.org
if your sever is self signed, then the plugin automatic works.
if not, some times you may need to use a special ca.

**Comment by JCanovas** [comment]
I have a service with a self-signed node (const options = {
    key: fs.readFileSync ('server-key.pem'),
    cert: fs.readFileSync ('server-crt.pem'),
    ca: fs.readFileSync ('ca-crt.pem'),
    requestCert: true,
    rejectUnauthorized: true
};
). How can I connect to the form with wss: //? When you talk about the previous comment that sometimes you need CA it's just the server? How could I connect? Thank you

**Comment by feixuwu** [comment]
Use wss, in  most tests, it works as expect. you can use my demo project to do the test, the demo project use wss too, you can see it works as expect.
If it not works on your server, please let me know.
发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: JCanovas <notifications@github.com>
发送时间: Sunday, August 19, 2018 12:09:29 AM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UEWebsocket] Secure Sockets? (#17)


I have a service with a self-signed node (const options = {
key: fs.readFileSync ('server-key.pem'),
cert: fs.readFileSync ('server-crt.pem'),
ca: fs.readFileSync ('ca-crt.pem'),
requestCert: true,
rejectUnauthorized: true
};
). How can I connect to the form with wss: //? When you talk about the previous comment that sometimes you need CA it's just the server? How could I connect? Thank you

―

**Comment by JCanovas** [comment]
works!! Thanks for the help!! My star to this project. Thank you. :)

**Comment by feixuwu** [comment]
Thanks very much!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: JCanovas <notifications@github.com>
发送时间: Sunday, August 19, 2018 8:50:39 AM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UEWebsocket] Secure Sockets? (#17)


works!! Thanks for the help!! My star to this project. Thank you. :)

―

**Comment by JCanovas** [comment]
another thing, :) referring to this topic. Where do I place this certificate in a compilation on android and how do I reference it from WebSocketContext.cpp? Can I include it in content or any other folder within the compilation? Thank you!!

**Comment by feixuwu** [comment]
Hi, I upload the basic android support, you can clone the latest version, and the demo project should works for android.

If you want to use in your project, you need copy the CA directory from my demo project content directory to your game content directory.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: JCanovas <notifications@github.com>
发送时间: Sunday, August 19, 2018 8:39:33 PM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UEWebsocket] Secure Sockets? (#17)


another thing, :) referring to this topic. Where do I place this certificate in a compilation on android and how do I reference it from WebSocketContext.cpp? Can I include it in content or any other folder within the compilation? Thank you!!

―

**Comment by JCanovas** [comment]
it works perfectly!! I can do great things with this plugin !! Thanks again for this excellent work.

**Comment by JCanovas** [comment]
you should delete the ca-bundle.pem of content. This twice in the project. The valid one is the one found in CA / ca-bundle.pem. Right? At least in my project I only have CA / ca-bundle.pem and it works perfectly with that alone. have you forgotten to delete it in the project? Thank you!!

**Comment by feixuwu** [comment]
Yes, thanks for you remind, I’ll delete the ca file in content tomorrow.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: JCanovas <notifications@github.com>
发送时间: Sunday, August 19, 2018 11:39:11 PM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UEWebsocket] Secure Sockets? (#17)


you should delete the ca-bundle.pem of content. This twice in the project. The valid one is the one found in CA / ca-bundle.pem. Right? At least in my project I only have CA / ca-bundle.pem and it works perfectly with that alone. have you forgotten to delete it in the project? Thank you!!

―
