### ISSUE TITLE
Example of using it in a C++ project

### ISSUE THREAD

**Issue by meetakshay99** [feixuwu/UEWebsocket#19]
Can you please provide an example of using the plugin in C++?

**Comment by meetakshay99** [comment]
I figured it out. So closing it.

**Comment by Hillshum** [comment]
@meetakshay99 Did you determine that existing documentation is sufficient? I'm facing this question now.

**Comment by Cl1608Ho** [comment]
as a general feedback, the docs kinda look "sufficient" for blueprint use. if you are so much into c++ i'd recommend reading the code (or the headers, that's where i'd assume comments for example).
