### ISSUE TITLE
Only works in editor (4.19)

### ISSUE THREAD

**Issue by crutchsoft** [feixuwu/UEWebsocket#22]
I created new project and copypasted plugin folder from UEWebsocket example.

I'm connecting and sending message from level blueprint. 
It works great in editor. But packaged game doesn't connect at all. 

Tryed both Dev and Shipment configuration. Firewall is disabled.

**Comment by feixuwu** [comment]
Did you copy the CA folder from the demo project content directory to your project content directory?
By the way, would you please post the url you connect?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: crutchsoft <notifications@github.com>
发送时间: Sunday, September 2, 2018 7:29:29 AM
收件人: feixuwu/UEWebsocket
抄送: Subscribed
主题: [feixuwu/UEWebsocket] Only works in editor (4.19) (#22)


I created new project and copypasted plugin folder from UEWebsocket example.

I'm connecting and sending message from level blueprint.
It works great in editor. But packaged game doesn't connect at all.

Tryed both Dev and Shipment configuration. Firewall is disabled.

―

**Comment by crutchsoft** [comment]
I downloaded earlyer version (without ca support) from git history, upgraded to 4.19 and now It's working.

But I'm not so good in plugin installation, so maybe I was doing something wrong in the first place. 

btw copying CA haven't done the trick for me. Url is ws://127.0.0.1:1234/

**Comment by sapaczb** [comment]
I am having the same issue. I have copied the CA folder from the demo project to my own project and everything works fine in the editor. However, when running a packaged build it no longer works. I noticed that the ca-bundle.pem file is empty when it's created using a shipping build, but not with an editor build.
