### ISSUE TITLE
Failure to build for Windows, missing UE4-WebSocket.lib

### ISSUE THREAD

**Issue by jakeRodelius** [feixuwu/UEWebsocket#24]
Whenever I download the project and build for a windows platform I receive the following errors.

```
UATHelper: Packaging (Windows (64-bit)):   ERROR: UBT ERROR: Failed to produce item: C:\... ...\UEWebsocket-master\UEWebsocket-master\Plugins\WebSocket\Binaries\Win64\UE4-WebSocket.lib

PackagingResults: Error: UBT ERROR: Failed to produce item: C:\... ...\UEWebsocket-master\UEWebsocket-master\Plugins\WebSocket\Binaries\Win64\UE4-WebSocket.lib
```
When I go to Plugins\WebSocket\Binaries\Win64 it is true that there isn't a UE4-WebSocket.lib file in there. How do I generate this file?

This is the provided .uproject with no additional edits. The plugin works great in editor but prevents me from building.

**Comment by feixuwu** [comment]
Hi，I tested build for win64, it success,
So would you please show me the error message?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jake <notifications@github.com>
发送时间: Tuesday, September 25, 2018 4:34:47 AM
收件人: feixuwu/UEWebsocket
抄送: Subscribed
主题: [feixuwu/UEWebsocket] Failure to build for Windows, missing UE4-WebSocket.lib (#24)


Whenever I download the project and build for a windows platform I receive the following errors.

UATHelper: Packaging (Windows (64-bit)):   ERROR: UBT ERROR: Failed to produce item: C:\... ...\UEWebsocket-master\UEWebsocket-master\Plugins\WebSocket\Binaries\Win64\UE4-WebSocket.lib

PackagingResults: Error: UBT ERROR: Failed to produce item: C:\... ...\UEWebsocket-master\UEWebsocket-master\Plugins\WebSocket\Binaries\Win64\UE4-WebSocket.lib


When I go to Plugins\WebSocket\Binaries\Win64 it is true that there isn't a UE4-WebSocket.lib file in there. How do I generate this file?

This is the provided .uproject with no additional edits. The plugin works great in editor but prevents me from building.

―

**Comment by jakeRodelius** [comment]
Thanks for your response, here is the full log when I build the project.

`UATHelper: Packaging (Windows (64-bit)): Running AutomationTool...
UATHelper: Packaging (Windows (64-bit)): Parsing command line: -ScriptsForProject=C:/UEWebsocket-master/UEWebsocket.uproject BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project=C:/UEWebsocket-master/UEWebsocket.uproject -cook -stage -archive -archivedirectory=C:/UEWebsocket-master -package -clientconfig=Development -ue4exe=UE4Editor-Cmd.exe -c
ompressed -pak -prereqs -nodebuginfo -targetplatform=Win64 -build -utf8output
UATHelper: Packaging (Windows (64-bit)): Setting up ProjectParams for C:\UEWebsocket-master\UEWebsocket.uproject
UATHelper: Packaging (Windows (64-bit)): ********** BUILD COMMAND STARTED **********
UATHelper: Packaging (Windows (64-bit)): Running: C:\Program Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket Win64 Development -Project=C:\UEWebsocket-master\UEWebsocket.uproject  C:\UEWebsocket-master\UEWebsocket.uproject -NoUBTMakefiles  -remoteini="C:\UEWebsocket-master" -skipdeploy -noxge -generatemanifest -NoHotReload
UATHelper: Packaging (Windows (64-bit)): Took 0.9440035s to run UnrealBuildTool.exe, ExitCode=0
UATHelper: Packaging (Windows (64-bit)): Running: C:\Program Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket Win64 Development -Project=C:\UEWebsocket-master\UEWebsocket.uproject  C:\UEWebsocket-master\UEWebsocket.uproject -NoUBTMakefiles  -remoteini="C:\UEWebsocket-master" -skipdeploy -noxge -NoHotReload -ignorejunk
UATHelper: Packaging (Windows (64-bit)):   Parsing headers for UEWebsocket
UATHelper: Packaging (Windows (64-bit)):     Running UnrealHeaderTool "C:\UEWebsocket-master\UEWebsocket.uproject" "C:\UEWebsocket-master\Intermediate\Build\Win64\UEWebsocket\Development\UEWebsocket.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed
UATHelper: Packaging (Windows (64-bit)):   Reflection code generated for UEWebsocket in 6.3649835 seconds
UATHelper: Packaging (Windows (64-bit)):   Performing 14 actions (4 in parallel)
UATHelper: Packaging (Windows (64-bit)):   [4/14] Resource PCLaunch.rc
UATHelper: Packaging (Windows (64-bit)):   PCH.UEWebsocket.cpp
UATHelper: Packaging (Windows (64-bit)):   Module.WebSocket.gen.cpp
UATHelper: Packaging (Windows (64-bit)):   Module.WebSocket.cpp
UATHelper: Packaging (Windows (64-bit)):   PCH.UELinkerFixups.cpp
UATHelper: Packaging (Windows (64-bit)):   [6/14] Resource PCLaunch.rc
UATHelper: Packaging (Windows (64-bit)):   UELinkerFixups.cpp
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(159): error C2653: 'FPaths': is not a class or namespace name
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(159): error C3861: 'ProjectSavedDir': identifier not found
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(165): error C2653: 'FPaths': is not a class or namespace name
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(165): error C3861: 'FileExists': identifier not found
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(168): error C2065: 'IFileManager': undeclared identifier
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(168): error C2065: 'FileManager': undeclared identifier
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(168): error C2653: 'IFileManager': is not a class or namespace name
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(168): error C3861: 'Get': identifier not found
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(169): error C2065: 'FileManager': undeclared identifier
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(174): error C2653: 'FPaths': is not a class or namespace name
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(174): error C3861: 'ProjectContentDir': identifier not found
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(175): error C2653: 'FFileHelper': is not a class or namespace name
UATHelper: Packaging (Windows (64-bit)):   C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(175): error C3861: 'LoadFileToString': identifier not found
UATHelper: Packaging (Windows (64-bit)):   GameMessage.cpp
UATHelper: Packaging (Windows (64-bit)):   GameMessage.gen.cpp
UATHelper: Packaging (Windows (64-bit)):   UEWebsocket.init.gen.cpp
UATHelper: Packaging (Windows (64-bit)):   EmptyClass.cpp
UATHelper: Packaging (Windows (64-bit)):   UEWebsocket.cpp
UATHelper: Packaging (Windows (64-bit)):   ERROR: UBT ERROR: Failed to produce item: C:\UEWebsocket-master\Plugins\WebSocket\Binaries\Win64\UE4-WebSocket.lib
PackagingResults: Error: UBT ERROR: Failed to produce item: C:\UEWebsocket-master\Plugins\WebSocket\Binaries\Win64\UE4-WebSocket.lib
UATHelper: Packaging (Windows (64-bit)):   Total build time: 55.41 seconds (Local executor: 0.00 seconds)
UATHelper: Packaging (Windows (64-bit)): Took 55.6039998s to run UnrealBuildTool.exe, ExitCode=5
UATHelper: Packaging (Windows (64-bit)): ERROR: Command failed (Result:5): C:\Program Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket Win64 Development -Project=C:\UEWebsocket-master\UEWebsocket.uproject  C:\UEWebsocket-master\UEWebsocket.uproject -NoUBTMakefiles  -remoteini="C:\UEWebsocket-master" -skipdeploy -noxge -NoHotRel
oad -ignorejunk. See logfile for details: 'UnrealBuildTool-2018.09.25-15.50.44.txt' 
UATHelper: Packaging (Windows (64-bit)):        (see C:\Users\M1\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.19\UAT_Log.txt for full exception trace)
PackagingResults: Error: Command failed (Result:5): C:\Program Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket Win64 Development -Project=C:\UEWebsocket-master\UEWebsocket.uproject  C:\UEWebsocket-master\UEWebsocket.uproject -NoUBTMakefiles  -remoteini="C:\UEWebsocket-master" -skipdeploy -noxge -NoHotReload -ignorejunk. See lo
gfile for details: 'UnrealBuildTool-2018.09.25-15.50.44.txt' 
UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=5 (5)
UATHelper: Packaging (Windows (64-bit)): BUILD FAILED
PackagingResults: Error: Unknown Error`

I am using Unreal version 4.19.2 and building for windows 64.

**Comment by feixuwu** [comment]
what is your engine version?

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by feixuwu** [comment]
I see, I will test on 4.19

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by feixuwu** [comment]
Hi, I submit a fix, please clone the latest version, it should fix this problem,
Thanks very much

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Jake <notifications@github.com>
发送时间: Wednesday, September 26, 2018 4:53:32 AM
收件人: feixuwu/UEWebsocket
抄送: xufeiwu; Comment
主题: Re: [feixuwu/UEWebsocket] Failure to build for Windows, missing UE4-WebSocket.lib (#24)


Thanks for your response, here is the full log when I build the project.

UATHelper: Packaging (Windows (64-bit)): Running AutomationTool... UATHelper: Packaging (Windows (64-bit)): Parsing command line: -ScriptsForProject=C:/UEWebsocket-master/UEWebsocket.uproject BuildCookRun -nocompile -nocompileeditor -installed -nop4 -project=C:/UEWebsocket-master/UEWebsocket.uproject -cook -stage -archive -archivedirectory=C:/UEWebsocket-master -package -clientconfig=Development -ue4exe=UE4Editor-Cmd.exe -c ompressed -pak -prereqs -nodebuginfo -targetplatform=Win64 -build -utf8output UATHelper: Packaging (Windows (64-bit)): Setting up ProjectParams for C:\UEWebsocket-master\UEWebsocket.uproject UATHelper: Packaging (Windows (64-bit)): ********** BUILD COMMAND STARTED ********** UATHelper: Packaging (Windows (64-bit)): Running: C:\Program Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket Win64 Development -Project=C:\UEWebsocket-master\UEWebsocket.uproject C:\UEWebsocket-master\UEWebsocket.uproject -NoUBTMakefiles -remoteini="C:\UEWebsocket-master" -skipdeploy -noxge -generatemanifest -NoHotReload UATHelper: Packaging (Windows (64-bit)): Took 0.9440035s to run UnrealBuildTool.exe, ExitCode=0 UATHelper: Packaging (Windows (64-bit)): Running: C:\Program Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket Win64 Development -Project=C:\UEWebsocket-master\UEWebsocket.uproject C:\UEWebsocket-master\UEWebsocket.uproject -NoUBTMakefiles -remoteini="C:\UEWebsocket-master" -skipdeploy -noxge -NoHotReload -ignorejunk UATHelper: Packaging (Windows (64-bit)): Parsing headers for UEWebsocket UATHelper: Packaging (Windows (64-bit)): Running UnrealHeaderTool "C:\UEWebsocket-master\UEWebsocket.uproject" "C:\UEWebsocket-master\Intermediate\Build\Win64\UEWebsocket\Development\UEWebsocket.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -installed UATHelper: Packaging (Windows (64-bit)): Reflection code generated for UEWebsocket in 6.3649835 seconds UATHelper: Packaging (Windows (64-bit)): Performing 14 actions (4 in parallel) UATHelper: Packaging (Windows (64-bit)): [4/14] Resource PCLaunch.rc UATHelper: Packaging (Windows (64-bit)): PCH.UEWebsocket.cpp UATHelper: Packaging (Windows (64-bit)): Module.WebSocket.gen.cpp UATHelper: Packaging (Windows (64-bit)): Module.WebSocket.cpp UATHelper: Packaging (Windows (64-bit)): PCH.UELinkerFixups.cpp UATHelper: Packaging (Windows (64-bit)): [6/14] Resource PCLaunch.rc UATHelper: Packaging (Windows (64-bit)): UELinkerFixups.cpp UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(159): error C2653: 'FPaths': is not a class or namespace name UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(159): error C3861: 'ProjectSavedDir': identifier not found UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(165): error C2653: 'FPaths': is not a class or namespace name UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(165): error C3861: 'FileExists': identifier not found UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(168): error C2065: 'IFileManager': undeclared identifier UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(168): error C2065: 'FileManager': undeclared identifier UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(168): error C2653: 'IFileManager': is not a class or namespace name UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(168): error C3861: 'Get': identifier not found UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(169): error C2065: 'FileManager': undeclared identifier UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(174): error C2653: 'FPaths': is not a class or namespace name UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(174): error C3861: 'ProjectContentDir': identifier not found UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(175): error C2653: 'FFileHelper': is not a class or namespace name UATHelper: Packaging (Windows (64-bit)): C:\UEWebsocket-master\Plugins\WebSocket\Source\WebSocket\Private\WebSocketContext.cpp(175): error C3861: 'LoadFileToString': identifier not found UATHelper: Packaging (Windows (64-bit)): GameMessage.cpp UATHelper: Packaging (Windows (64-bit)): GameMessage.gen.cpp UATHelper: Packaging (Windows (64-bit)): UEWebsocket.init.gen.cpp UATHelper: Packaging (Windows (64-bit)): EmptyClass.cpp UATHelper: Packaging (Windows (64-bit)): UEWebsocket.cpp UATHelper: Packaging (Windows (64-bit)): ERROR: UBT ERROR: Failed to produce item: C:\UEWebsocket-master\Plugins\WebSocket\Binaries\Win64\UE4-WebSocket.lib PackagingResults: Error: UBT ERROR: Failed to produce item: C:\UEWebsocket-master\Plugins\WebSocket\Binaries\Win64\UE4-WebSocket.lib UATHelper: Packaging (Windows (64-bit)): Total build time: 55.41 seconds (Local executor: 0.00 seconds) UATHelper: Packaging (Windows (64-bit)): Took 55.6039998s to run UnrealBuildTool.exe, ExitCode=5 UATHelper: Packaging (Windows (64-bit)): ERROR: Command failed (Result:5): C:\Program Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket Win64 Development -Project=C:\UEWebsocket-master\UEWebsocket.uproject C:\UEWebsocket-master\UEWebsocket.uproject -NoUBTMakefiles -remoteini="C:\UEWebsocket-master" -skipdeploy -noxge -NoHotRel oad -ignorejunk. See logfile for details: 'UnrealBuildTool-2018.09.25-15.50.44.txt' UATHelper: Packaging (Windows (64-bit)): (see C:\Users\M1\AppData\Roaming\Unreal Engine\AutomationTool\Logs\C+Program+Files+Epic+Games+UE_4.19\UAT_Log.txt for full exception trace) PackagingResults: Error: Command failed (Result:5): C:\Program Files\Epic Games\UE_4.19\Engine\Binaries\DotNET\UnrealBuildTool.exe UEWebsocket Win64 Development -Project=C:\UEWebsocket-master\UEWebsocket.uproject C:\UEWebsocket-master\UEWebsocket.uproject -NoUBTMakefiles -remoteini="C:\UEWebsocket-master" -skipdeploy -noxge -NoHotReload -ignorejunk. See lo gfile for details: 'UnrealBuildTool-2018.09.25-15.50.44.txt' UATHelper: Packaging (Windows (64-bit)): AutomationTool exiting with ExitCode=5 (5) UATHelper: Packaging (Windows (64-bit)): BUILD FAILED PackagingResults: Error: Unknown Error

I am using Unreal version 4.19.2 and building for windows 64.

―

**Comment by jakeRodelius** [comment]
Fantastic, it works! Thanks for doing this so quickly, keep up the great work!
