### ISSUE TITLE
Access violation exception when using connect with a malformed URL

### ISSUE THREAD

**Issue by Ruhrpottpatriot** [feixuwu/UEWebsocket#3]
This happened to me yesterday and I can't remember the details anymore, but when using the `Connect` blueprint node (and I guess by extension the c++ method also) the game crashes with an access violation.
I know the URL wasn't empty and as far as I can remember it was like this: `ws://localho`

I think there are some safety checks are missing in the `UWebSocketBase::Connect(const FString& uri)` method.

**Comment by feixuwu** [comment]
Thanks, I’ll check the problem

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Robert Logiewa<mailto:notifications@github.com>
发送时间: 2017年9月9日 0:08
收件人: feixuwu/UEWebsocket<mailto:UEWebsocket@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: [feixuwu/UEWebsocket] Access violation exception when using connect with a malformed URL (#3)


This happened to me yesterday and I can't remember the details anymore, but when using the Connect blueprint node (and I guess by extension the c++ method also) the game crashes with an access violation.
I know the URL wasn't empty and as far as I can remember it was like this: ws://localho

I think there are some safety checks are missing in the UWebSocketBase::Connect(const FString& uri) method.

―

**Comment by feixuwu** [comment]
fixed the problem, when the address is invalid, will cause a NULL pointer crash.
