### ISSUE TITLE
 Please correct the warning in WebSocket.Build.cs

### ISSUE THREAD

**Issue by MrWoWander** [feixuwu/UEWebsocket#33]
warning: Modules must specify an explicit precompiled header (eg. PrivatePCHHeaderFile = "Public/WebSocket.h") from UE 4.21 onwards.

**Comment by feixuwu** [comment]
currently, the plugin still need to support 4.20, fix the warning on 4.21 may cause 4.20 build error.
after 4.22 released, 4.20 will not be supported, then I will submit the fix.

**Comment by Smoozilla** [comment]
@feixuwu Hello and many thanks for this plugin

Build is failing for me in 4.22 (released a few days ago) but remains working fine in 4.21.2

No rush, and thanks again for this great project!

**Comment by feixuwu** [comment]
ok, I will fix it in the next few days, thanks very much.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by feixuwu** [comment]
4.22 support have submited
