### ISSUE TITLE
if you have a problem with linking involved with open ssl, try this.

### ISSUE THREAD

**Issue by JackAloneDev** [feixuwu/UEWebsocket#37]
copy overwrite **websockets_static.lib** from unreal engine's folder to plugin's folder
in my case:
copy from (Engine)
C:\Users\jack\Documents\GitHub\UnrealEngine\Engine\Source\ThirdParty\libWebSockets\libwebsockets\lib\ **Win64** \VS2015\Release\ **websockets_static.lib**
to (My Project)
C:\Users\jack\Documents\Unreal Projects\My Project\Plugins\WebSocket\Source\WebSocket\ThirdParty\lib\ **Win64** \ **websockets_static.lib**

Do the same for all platforms.
promoted launcher version is same too.

**Comment by feixuwu** [comment]
the 4.22 support is in progress, I have finished most of the work. I think the work will finish this weekend.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JackAloneDev** [comment]
Thank you

**Comment by JackAloneDev** [comment]
Do not try this I mentioned. It's not working properly. Sorry.
