### ISSUE TITLE
SendText causes crash, after being called few hundred times.

### ISSUE THREAD

**Issue by jans32** [feixuwu/UEWebsocket#5]
I have this code running in a loop timer, sending client movement to the server
```
UInputMovement* Message = NewObject<UInputMovement>(this);

		Message->Type = "Movement"; // FName
		Message->UserId = 15564; // int
		Message->X = Velocity.X; // float
		Message->Y = Velocity.Y; // float
		Message->Rot = UpdateRotation().Yaw; // float

		FString Data;
		UWebSocketBlueprintLibrary::ObjectToJson(Message, Data);

		OwningPawn->WebSocket->SendText(Data);
``` 
It is running for a minute or so and then crashes. VS Debug info [https://i.imgur.com/aGSJj3V.png](https://i.imgur.com/aGSJj3V.png) Engine ver - 4.17.2 Launcher build.

**Comment by feixuwu** [comment]
hi, is the WebSocket member a pure c++ pointer or a UPROPERTY member?
if it is a pure c++ pointer, the WebSocket may be destroy by GC.

**Comment by jans32** [comment]
Hi, yes it was pure, didn't think about the garbage collection. Adding UPROPERTY seems to have fixed the issue. Many thanks for the quick reply. P.S Really cool plugin, love it.
