### ISSUE TITLE
Wrong Connect URL fails silently

### ISSUE THREAD

**Issue by TheTyrius** [feixuwu/UEWebsocket#52]
When trying to connect to an address omitting "ws://" prefix or using an invalid hostname, the connection seems to fail silently (e.g. no "OnConnectError" is thrown). How difficult would it be to throw an OnConnectError (or similar) for "Unsupported Protocol" and/or "Invalid Hostname" errors? 
Might be related to #3

**Comment by TheTyrius** [comment]
> 2019.06.11-19.01.15 [DESKTOP-ED6THIO-1404] 01052.403: WebSocket: libwebsocket connect error:getaddrinfo failed
> 2019.06.11-19.01.15 [DESKTOP-ED6THIO-1404] 01052.403: WebSocket: create client connect fail
> 2019.06.11-19.01.21 [DESKTOP-ED6THIO-1404] 01058.288: WebSocket: libwebsocket connect error:getaddrinfo failed
> 2019.06.11-19.01.21 [DESKTOP-ED6THIO-1404] 01058.288: WebSocket: create client connect fail
> 2019.06.11-19.01.27 [DESKTOP-ED6THIO-1404] 01064.166: WebSocket: libwebsocket connect error:getaddrinfo failed
> 2019.06.11-19.01.27 [DESKTOP-ED6THIO-1404] 01064.166: WebSocket: create client connect fail
> 

I found this in the logs, which happens on invalid hostname, would it be possible to throw this as OnConnectError in addition to logging, so the game-logic can adapt? Or is this something I can already detect and am missing how?

**Comment by TheTyrius** [comment]
Is it possible that this also stalls the gamethread until "getaddrinfo" fails?

**Comment by feixuwu** [comment]
yes, u are right, maybe should add a ret value, to let user know connect fail

**Comment by TheTyrius** [comment]
On a slightly different note: Since the "connect" all creates the websocket-base-object that is needed to bind events, I can only bind onConnectComplete/onMessageReceived _after_ connecting. Is it guaranteed somehow that I'm not missing one of these events? Ideally I'd say bind them before connecting, but that is not possible in this case. Is that relying on the fact that "connecting takes some time, it's fine" or does something internally prevent this race condition?

**Comment by feixuwu** [comment]
hi, I add an out value on connect function to check if the connect fail before network, u can check it after call the connect function, 
pull the latest content.
