### ISSUE TITLE
Request finished in ~60 sec 101 

### ISSUE THREAD

**Issue by git-knight** [feixuwu/UEWebsocket#55]
I'm trying to use this plugin but i'm having a problem: the connection "dies" after 55-60 sec of being connected even if i send different messages and receive server responses to them. while other 2 different clients have no such problem with the same server

at the moment it closes i receive
LWS_CALLBACK_DEL_POLL_FD and then
LWS_CALLBACK_WSI_DESTROY

anyone has any ideas?

**Comment by feixuwu** [comment]
U need to set the websocket object to a class member and wrap with UPROPERTY,
Your object is GC by unreal engine 4 system.


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: git-knight <notifications@github.com>
发送时间: Sunday, June 30, 2019 8:08:21 PM
收件人: feixuwu/UEWebsocket
抄送: Subscribed
主题: [feixuwu/UEWebsocket] Request finished in ~60 sec 101 (#55)


I'm trying to use this plugin but i'm having a problem: the connection "dies" after 55-60 sec of being connected even if i send different messages and receive server responses to them. while other 2 different clients have no such problem with the same server

at the moment it closes i receive
LWS_CALLBACK_DEL_POLL_FD and then
LWS_CALLBACK_WSI_DESTROY

anyone has any ideas?

―

**Comment by git-knight** [comment]
yup it looks like that was it, no more random Request finished
