### ISSUE TITLE
Integrating into a custom plugin

### ISSUE THREAD

**Issue by weiiiiii** [feixuwu/UEWebsocket#6]
Hi,

I will like to integrate this into a custom plugin of mine but there were some issues when doing so, such as redifinition of sockaddr. I will like to know where the source code for websocket_static.lib is from as it is different from the one in unreal engine. Is it from either https://libwebsockets.org/git/libwebsockets/ or https://github.com/warmcat/libwebsockets?

**Comment by feixuwu** [comment]
yes,what is the error message?

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by feixuwu** [comment]
I guess you means name corrupt, you can change your struct or class name to fix it.
