### ISSUE TITLE
Critical error when closing the project

### ISSUE THREAD

**Issue by MrWoWander** [feixuwu/UEWebsocket#63]
When I run the project in the editor, run the code, everything works fine. When closing the socket too. But after I start to close the editor, an error appears.

![error](https://a.radikal.ru/a13/1910/f9/80568c9b777e.png)

He can't destroy the object

**Comment by Jungleboy76** [comment]
I get an error too after closing the editor or build in 4.23.0.
Error after closing the editor:

Assertion failed: GetFName() == NAME_None

UE4Editor_WebSocket!UWebSocketContext::`scalar deleting destructor'()
UE4Editor_WebSocket!UWebSocketContext::BeginDestroy()  [d:\********************\4_23\*********\plugins\websocket\source\websocket\private\websocketcontext.cpp:73]

**Comment by feixuwu** [comment]
hi, please get latest content, this problem fixed

**Comment by MrWoWander** [comment]
thx
