### ISSUE TITLE
Can't connect to server on Android with CPP code

### ISSUE THREAD

**Issue by Yiwozai** [feixuwu/UEWebsocket#68]
在我这出现了这种情况：蓝图写逻辑能跑通Win64和Android平台，C++写的只能在Win64运行，打包之后运行在安卓上连不上服务器。 感觉像是打包没有成功包含三方库，但尝试了多次也没找到正确方法，不知道具体是什么问题。

Project in UE4.21
[WebAndroidCPP.zip](https://github.com/feixuwu/UEWebsocket/files/3835726/WebAndroidCPP.zip)

Blueprint can run in Win64 and Android, but C++ logic can only run in Win64. Seems that it's because the ThirdParty. Wonder what's the real problem.

**Comment by feixuwu** [comment]
4.21的，需要从4.21的tag或者分支下载版本，不要用master版本

**Comment by Yiwozai** [comment]
谢谢回复，项目不再跟进开发，不能给你下一步反馈了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xufeiwu"<notifications@github.com&gt;; 
发送时间: 2020年3月21日(星期六) 中午12:17
收件人: "feixuwu/UEWebsocket"<UEWebsocket@noreply.github.com&gt;; 
抄送: "忆我在"<yiwozai@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [feixuwu/UEWebsocket] Can&#39;t connect to server on Android with CPP code (#68)





 
4.21的，需要从4.21的tag或者分支下载版本，不要用master版本
