### ISSUE TITLE
[Issue][4.23.1][Android package]

### ISSUE THREAD

**Issue by C-Abner** [feixuwu/UEWebsocket#70]
C:/NVPACK/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lwebsockets
    C:/NVPACK/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lssl
    C:/NVPACK/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: cannot find -lcrypto

**Comment by C-Abner** [comment]
@feixuwu    Need help for a problem on package android ASTC.

**Comment by RogueSheep-nl** [comment]
@C-Abner did you manage to fix this issue? Please share your solution.
