### ISSUE TITLE
UE4.24 support without HTML5

### ISSUE THREAD

**Issue by michela** [feixuwu/UEWebsocket#71]
With removal of HTML in UE4.24, the plugin gets PLATFORM_HTML5 errors. 

Removing all the PLATFORM_HTML preprocessors but still getting errors as below

> 
> [1>  [1/2] UE4Editor-WebSocket.dll
> 1>     Creating library D:\Perforce\michela_ZOD_3960\projects\datafarms\ue4\DataFarmsPrototype 4.24\DataFarmsPrototype\Plugins\WebSocket\Intermediate\Build\Win64\UE4Editor\Development\WebSocket\UE4Editor-WebSocket.suppressed.lib and object D:\Perforce\michela_ZOD_3960\projects\datafarms\ue4\DataFarmsPrototype 4.24\DataFarmsPrototype\Plugins\WebSocket\Intermediate\Build\Win64\UE4Editor\Development\WebSocket\UE4Editor-WebSocket.suppressed.exp
> 1>Module.WebSocket.1_of_2.cpp.obj : error LNK2019: unresolved external symbol lws_client_connect_via_info referenced in function "public: bool __cdecl UWebSocketBase::Connect(class FString const &,class TMap<class FString,class FString,class FDefaultSetAllocator,struct TDefaultMapHashableKeyFuncs<class FString,class FString,0> > const &)" (?Connect@UWebSocketBase@@QEAA_NAEBVFString@@AEBV?$TMap@VFString@@V1@VFDefaultSetAllocator@@U?$TDefaultMapHashableKeyFuncs@VFString@@V1@$0A@@@@@@Z)
> 1>Module.WebSocket.1_of_2.cpp.obj : error LNK2019: unresolved external symbol lws_add_http_header_by_name referenced in function "public: bool __cdecl UWebSocketBase::ProcessHeader(unsigned char * *,unsigned char *)" (?ProcessHeader@UWebSocketBase@@QEAA_NPEAPEAEPEAE@Z)
> 1>Module.WebSocket.1_of_2.cpp.obj : error LNK2019: unresolved external symbol lws_write referenced in function "public: void __cdecl UWebSocketBase::ProcessWriteable(void)" (?ProcessWriteable@UWebSocketBase@@QEAAXXZ)
> 1>Module.WebSocket.1_of_2.cpp.obj : error LNK2019: unresolved external symbol lws_set_wsi_user referenced in function "public: virtual void __cdecl UWebSocketBase::BeginDestroy(void)" (?BeginDestroy@UWebSocketBase@@UEAAXXZ)
> 1>Module.WebSocket.2_of_2.cpp.obj : error LNK2001: unresolved external symbol lws_extension_callback_pm_deflate
> 1>Module.WebSocket.2_of_2.cpp.obj : error LNK2019: unresolved external symbol lws_create_context referenced in function "public: void __cdecl UWebSocketContext::CreateCtx(void)" (?CreateCtx@UWebSocketContext@@QEAAXXZ)
> 1>Module.WebSocket.2_of_2.cpp.obj : error LNK2019: unresolved external symbol lws_service referenced in function "public: virtual void __cdecl UWebSocketContext::Tick(float)" (?Tick@UWebSocketContext@@UEAAXM@Z)
> 1>Module.WebSocket.2_of_2.cpp.obj : error LNK2019: unresolved external symbol lws_callback_on_writable_all_protocol referenced in function "public: virtual void __cdecl UWebSocketContext::Tick(float)" (?Tick@UWebSocketContext@@UEAAXM@Z)
> 1>Module.WebSocket.2_of_2.cpp.obj : error LNK2019: unresolved external symbol lws_wsi_user referenced in function "public: static int __cdecl UWebSocketContext::callback_echo(struct lws *,enum lws_callback_reasons,void *,void *,unsigned __int64)" (?callback_echo@UWebSocketContext@@SAHPEAUlws@@W4lws_callback_reasons@@PEAX2_K@Z)
> 1>D:\Perforce\michela_ZOD_3960\projects\datafarms\ue4\DataFarmsPrototype 4.24\DataFarmsPrototype\Plugins\WebSocket\Binaries\Win64\UE4Editor-WebSocket.dll : fatal error LNK1120: 9 unresolved externals
> 1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.MakeFile.Targets(44,5): error MSB3075: The command ""D:\Program Files\Epic Games\UE_4.24\Engine\Build\BatchFiles\Build.bat" DataFarmsPrototypeEditor Win64 Development -Project="D:\Perforce\michela_ZOD_3960\projects\datafarms\ue4\DataFarmsPrototype 4.24\DataFarmsPrototype\DataFarmsPrototype.uproject" -WaitMutex -FromMsBuild" exited with code 5. Please verify that you have sufficient rights to run this command.
> 1>Done building project "DataFarmsPrototype.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 1 skipped ==========](url)
>

**Comment by michela** [comment]
[diff.txt](https://github.com/feixuwu/UEWebsocket/files/3942544/diff.txt)

Pls see diff attached for how I removed HTML5 refs

**Comment by ericblade** [comment]
i'm confused, are you saying that HTML is no longer supported in UE, or that you have configured it out?

I haven't touched 4.24 yet, but I see changelogs for HTML platform.  I also see mention that the UE WebSocketNetworking plugin is now multiplatform..

**Comment by michela** [comment]
Yes epic have removed HTML platform and moved it to an optional community repos

https://docs.unrealengine.com/en-US/Platforms/HTML5/GettingStarted/index.html

**Comment by michela** [comment]
I've been unable to get websockets working in UE4.24 yet - it would be great if HTML5 could be removed from this plugin to support this. 

The new built-in ":Experimental Websocket Networking Plugin" doesn't appear to be exposed to Blueprints.

**Comment by Jungleboy76** [comment]
i got it working for Win64 no other tested ...
ok im a big C++ Noob but i made the same changes like u michela ... but still got some errors.

I got some errors that the UE4 source files arent found.
So i changed the UE4 includes direct to the path of UE4 source files and it worked / compiled.

**Comment by feixuwu** [comment]
I have submitted support 4.24, I tested for win64 win32 android and ios,
there still some build warnning, I will fix it later time.

**Comment by michela** [comment]
Thanks!
