### ISSUE TITLE
OnConnectError not called if server offline

### ISSUE THREAD

**Issue by michela** [feixuwu/UEWebsocket#8]
To repro, stop server, changing ws URL to server you control, stop that server, 

run sample project

Output log shows:
[WebSocket: Error: libwebsocket connect error:](url)

but OnConnectError is never called when bound as shown in sample

![screenshot 22](https://user-images.githubusercontent.com/99073/33812897-a5971aee-de74-11e7-90a5-84c5cfa4a056.png)

**Comment by feixuwu** [comment]
hi, please change the print string to another string, the OnConnectError will call,
but the error string maybe  empty, so you may can not see the output.

**Comment by michela** [comment]
That was it. Thanks
