### ISSUE TITLE
OnReceiveMessage works only once

### ISSUE THREAD

**Issue by weiiiiii** [feixuwu/UEWebsocket#9]
Hi,

I have integrated your plugin into my project and found a bug that exist in my project and your sample project. Connecting to a websocket server works, sending message to that server works too. When it comes to receiving message from websocket server, it only receives once. Any message after the second message is empty. I have been debugging and I found that UWebSocketContext::callback_echo(), in case LWS_CALLBACK_CLIENT_RECEIVE, len is 0 when I send the same message again from my websocket server.

**Comment by feixuwu** [comment]
Hi, thanks for your email, I tested the sample project, there’s no such bug.
Would you please show me the code you use?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by feixuwu** [comment]
By the way, did you confirmed the server send you message?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by weiiiiii** [comment]
Let me check if I can send you a sample websocket server to you. We are using a c# websocket server.

**Comment by feixuwu** [comment]
I suggest first debug your server, to check if the server send valid message, it is not difficult, a simple server can do test.

**Comment by weiiiiii** [comment]
I have checked that whatever our server is working by testing it with another c# websocket client, where sending and receiving works as expected, regardless of the number of times i tried. However, when we tested one of our projects integrated with your plugin and with the project from this git, only the first message received by your plugin has content and subsequent messages are empty, even though my server is sending the exact message. 

Here is a download link for the sample server we use.
https://my.pcloud.com/publink/show?code=XZrgkF7Zu0GsU501qWpTfPyfHcxgVHWhX2z7

This sample server will use url as such, "ws://localhost:<port_number>/<room_name>". The server will ask for a <port_number>, followed by a <room_name>. 

E.g. 1) To set the server's url as "ws://localhost:9001", do the following
`type 9001`
`press enter`
`press enter`

E.g. 2) To set the server's url as "ws://localhost:9001/myroom", do the following
`type 9001`
`press enter`
`type /myroom`
`press enter`

**Comment by feixuwu** [comment]
Hi, this is not the way to do a test😊, I don’t need a binary server to test, the demo project have an  node.js test server in server directory,
I just want to help you to find out your server bug or you client use bug…..

The demo project, if you run it in editor default, it connect to wss://echo.websocket.org (a public websocket echo server) and send a message and receive an echo message,
It will show the receive message is no problem.



发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________

**Comment by imtrobin** [comment]
Hi, I'm facing the same issue. I'm using the echo server from here. 

https://github.com/deniszykov/WebSocketListener

Your default sample will print "Hi, I'm websocket" twice, then on server it receives blank data.

**Comment by feixuwu** [comment]
there's a test server on project, you can test it or with the wss://echo.websocket.org for test.
this is not a bug, you can not send message before connected, you need to send message after connect success.

**Comment by imtrobin** [comment]
Hi, I send message after connect success of course, you can try it out with the default sample echo server in link.

I checked that both WebSocketListener and WebSocketSTA Sharp both don't support context switch, maybe that is the cause.

https://github.com/vtortola/WebSocketListener/wiki/Deflate-extension

In your libwebsocket you turn it on context switch, I see unreal default LwsWebSocketsManager do not turn that on, they only use client_max_window_bits.

**Comment by tgrothm** [comment]
I am facing the same issue.
I use a C# Server that works perfectly with a c# client, but when I connect using the Engine and this plugin I can only receive one Message. 
All following messages call 'ReceiveData' with an empty string although I know they aren't empty.

**Comment by tgrothm** [comment]
just found out that using "wss://echo.websocket.org" works.
So this has to be a c#-server-side issue

**Comment by feixuwu** [comment]
if connect success, the data send/receive should works, did you send binary data so the client can not see the text?

if you want send binary, you may do base64 endode before send, and do base64 decode after receive.


?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tgrothm** [comment]
It's probably connected to this: https://github.com/sta/websocket-sharp/issues/505

**Comment by feixuwu** [comment]
I think the reason is you send binary data, maybe try send text and do a test?

anyway, I will do a test this weekend to found the reason.

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tgrothm** [comment]
So... I found a workaround.
In WebSocket.cs (Line 2422):
Original:

```c#
byte[] found;
if (!cache.TryGetValue (_compression, out found)) {
found = new WebSocketFrame (
  Fin.Final,
  opcode,
  data.Compress (_compression),
  _compression != CompressionMethod.None,
  false
 )
  .ToArray ();

  cache.Add (_compression, found);
}
```

My version with deactivated compression:
```c#
byte[] found;
if (!cache.TryGetValue(CompressionMethod.None, out found))
{
found = new WebSocketFrame(
  Fin.Final,
  opcode,
  data.Compress(CompressionMethod.None),
  false,
  false
  )
  .ToArray();

  cache.Add(_compression, found);
}
```

**Comment by Tim-McGuinness** [comment]
For anyone that would like a non server-side solution to this you can just disable the WebSocket compression extensions (C# servers don't seem to like it). https://github.com/feixuwu/UEWebsocket/issues/58
